In [ ]:
import numpy as np

In [ ]:
def TwoByTwoDet(arr):
    return (arr[0][0] * arr[1][1]) - (arr[1][0] * arr[0][1]) 

In [3]:
def NByNDet(arr):
    #print(arr)
    shape = arr.shape
    if shape[0] != shape[1]:
        print("bad input")
        return None
    if shape[0] == 2:
        return TwoByTwoDet(arr)
    n = 0
    detCount = 0
    indexList = np.arange(0, shape[0])
    while n < shape[0]:
        rows = indexList[np.arange(len(indexList))!=n] #Get all rows except the one at te index
        columns = indexList[1:len(indexList)] #Get all columns except the first. 
        newArr = arr[np.ix_(rows, columns)].copy() # select the rows with indexes rows,columns
        if n % 2 == 0:
            result = NByNDet(newArr) #use the det of the sub matrix
            #print(result)
            detCount = detCount + (arr[n][0] * result)
        else: # for the plus minus rule
            result = NByNDet(newArr)
            detCount = detCount - (arr[n][0] * result)
        #print (detCount)
        n = n + 1
    return detCount


### Problem 2

In [4]:
arr = np.array([[2,6],[-7,2]])

In [5]:
import numpy.linalg as lin
lin.det(arr)

46.0

In [6]:
NByNDet(arr)

46

### Problem 4

In [7]:
arr = np.array([[2,-4,3],[3,1,2],[1,4,-1]])

In [8]:
lin.det(arr)

-5.0000000000000036

In [9]:
NByNDet(arr)

-5

### Problem 8

In [10]:
arr = np.array([[3,5,-8,4],[0,-2,3,-7],[0,0,1,5], [0,0,0,2]])

In [11]:
lin.det(arr)

-12.0

In [12]:
NByNDet(arr)

-12

In [13]:
EightByEightArray = np.array([[1,3,2,3,6,2,6,3], [1,9,3,2,1,6,9,1], [1,9,3,5,3,5,2,9], [6,8,2,3,6,3,5,4], [1,5,6,4,8,9,5,4],[2,4,5,3,6,7,5,4], [1,4,5,6,7,8,4,3], [2,4,3,2,5,7,4,1]])

In [14]:
EightByEightArray

array([[1, 3, 2, 3, 6, 2, 6, 3],
       [1, 9, 3, 2, 1, 6, 9, 1],
       [1, 9, 3, 5, 3, 5, 2, 9],
       [6, 8, 2, 3, 6, 3, 5, 4],
       [1, 5, 6, 4, 8, 9, 5, 4],
       [2, 4, 5, 3, 6, 7, 5, 4],
       [1, 4, 5, 6, 7, 8, 4, 3],
       [2, 4, 3, 2, 5, 7, 4, 1]])

In [15]:
lin.det(EightByEightArray)

139224.00000000012

In [16]:
NByNDet(EightByEightArray)

139224

#### Cramer's rule

In [17]:
#Input: A coeficent matrix, A and an answer matrix B. 
#Output: A matrix X which solves the equation AX = B.

In [18]:
#Create solution vector
# Get overall determinant.
#Set each value in solution = determinant of replacing array with the answer matrix. 

In [56]:
def SolveLinearEquationWithCramer(coefMatrix, answerMatrix):
    det = NByNDet(coefMatrix)
    answerVector = []
    numColumns = coefMatrix.shape[1]
    for i in range(numColumns):
        tempMatrix = coefMatrix.copy()
        tempMatrix[:,i] = answerMatrix
        varDet = NByNDet(tempMatrix)
        varResult = varDet/det
        answerVector.append(varResult)
        print(varResult)
    return answerVector
        

### Problem 1

In [67]:
coefMatrix = np.array([[5,7],[2,4]])
coefMatrix

array([[5, 7],
       [2, 4]])

In [68]:
answerMatrix = np.array([3,1])
answerMatrix

array([3, 1])

In [69]:
sol = SolveLinearEquationWithCramer(coefMatrix, answerMatrix) 
sol

0.8333333333333334
-0.16666666666666666


[0.8333333333333334, -0.16666666666666666]

### Problem 3

In [70]:
coefMatrix = np.array([[3,-2],[-5,6]])
coefMatrix

array([[ 3, -2],
       [-5,  6]])

In [71]:
answerMatrix = np.array([7,-5])
answerMatrix

array([ 7, -5])

In [72]:
sol = SolveLinearEquationWithCramer(coefMatrix, answerMatrix)
sol


4.0
2.5


[4.0, 2.5]

### Problem 6

In [73]:
coefMatrix = np.array([[2,1,1],[-1,0,2], [3,1,3]])
coefMatrix

array([[ 2,  1,  1],
       [-1,  0,  2],
       [ 3,  1,  3]])

In [74]:
answerMatrix = np.array([4,2,-2])
answerMatrix

array([ 4,  2, -2])

In [75]:
sol = SolveLinearEquationWithCramer(coefMatrix, answerMatrix) #1,3,6

-4.0
13.0
-1.0
